// GENERATED by scripts/gen.mjs from docs/reference/optimus-design — do not edit.
// @ts-nocheck
import React from "react";
import * as DS from "../index";

const mono = { fontFamily: 'var(--font-mono)', fontSize: 11, letterSpacing: '.08em', textTransform: 'uppercase', color: 'var(--muted)' };

function Spec({ label, children, col }) {
  return (
    <div style={{ display: 'grid', gridTemplateColumns: '160px minmax(0,1fr)', gap: 24, padding: '24px 0', borderTop: '1px solid var(--rule-soft)', alignItems: col ? 'start' : 'center' }}>
      <div style={{ ...mono, color: 'var(--muted-2)', paddingTop: col ? 4 : 0 }}>{label}</div>
      <div style={{ display: 'flex', flexDirection: col ? 'column' : 'row', gap: 16, flexWrap: col ? 'nowrap' : 'wrap', alignItems: col ? 'stretch' : 'center', minWidth: 0 }}>{children}</div>
    </div>
  );
}

function Block({ id, index, name, file, children }) {
  return (
    <section id={id} style={{ padding: '64px 0', borderTop: '1px solid var(--ink)', scrollMarginTop: 0 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: 16, marginBottom: 24, flexWrap: 'wrap' }}>
        <div style={{ display: 'flex', gap: 16, alignItems: 'baseline' }}>
          <span style={{ ...mono, color: 'var(--ink)' }}>{index}</span>
          <h2 style={{ margin: 0, fontWeight: 700, fontSize: 40, letterSpacing: '-.04em', lineHeight: 1, color: 'var(--ink)' }}>{name}<span style={{ color: 'var(--molten)' }}>.</span></h2>
        </div>
        <code style={mono}>{file}</code>
      </div>
      {children}
    </section>
  );
}

const GROUPS = [
  ['Core', ['Button', 'ArrowLink', 'Eyebrow', 'Headline', 'Tag', 'StatusDot', 'Wordmark', 'Rule']],
  ['Forms', ['Input', 'Select', 'Checkbox', 'Radio', 'Switch']],
  ['Display', ['Card', 'Stat', 'ProcessStep']],
  ['Navigation', ['Tabs', 'NavBar']],
  ['Feedback', ['Dialog', 'Toast', 'Tooltip']],
  ['Primitives', ['Icon', 'Spinner', 'ButtonGroup', 'Link', 'Text', 'Badge', 'Avatar', 'Skeleton']],
  ['Fields', ['Label', 'FormHint', 'FormField', 'TextField', 'TextArea', 'Dropdown', 'MultiSelect', 'Slider', 'Stepper', 'DatePicker', 'FileUpload']],
  ['Data', ['Accordion', 'StatCard', 'EmptyState', 'FilterTabs', 'List', 'Table', 'DataGrid']],
  ['Wayfinding', ['Breadcrumb', 'Pagination', 'StepIndicator', 'Sidebar', 'CommandPalette']],
  ['Status', ['Alert', 'Banner', 'Progress']],
  ['Overlays', ['Drawer', 'Popover', 'DropdownMenu']],
  ['Layout', ['Container', 'Stack', 'Grid', 'AspectRatio', 'PageHero', 'SectionHeader', 'PageShell', 'PageTransition']],
];

function Sidebar() {
  let n = 0;
  return (
    <aside style={{ position: 'sticky', top: 0, height: '100vh', overflowY: 'auto', padding: '40px 32px', borderRight: '1px solid var(--rule-soft)', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', gap: 32 }}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        <DS.Wordmark size="nav" />
        <span style={mono}>Components · v1.0</span>
      </div>
      {GROUPS.map(([g, items]) => (
        <div key={g} style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          <div style={{ ...mono, color: 'var(--ink)' }}>{g}</div>
          {items.map(it => { n++; return (
            <a key={it} href={'#' + it.toLowerCase()} style={{ display: 'flex', gap: 12, fontSize: 15 }}>
              <span style={{ ...mono, fontSize: 10, width: 18, paddingTop: 3 }}>{String(n).padStart(2, '0')}</span>{it}
            </a>); })}
        </div>
      ))}
    </aside>
  );
}


function DrawerDemo() { const [o, setO] = React.useState(false); const { Drawer, Button, Checkbox, Radio } = DS; return <>
  <Button variant="secondary" onClick={() => setO(true)}>Open filters</Button>
  <Drawer open={o} onClose={() => setO(false)} eyebrow="Projects" title="Filter" accent="the archive" description="Narrow fourteen pieces to the ones you need." footer={<><Button variant="secondary" onClick={() => setO(false)}>Reset</Button><Button onClick={() => setO(false)}>Apply</Button></>}>
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}><Checkbox label="Live only" defaultChecked /><Checkbox label="Include prototypes" /><Radio label="Platform" options={['Web', 'iOS', 'Both']} /></div>
  </Drawer></>; }
function PaletteDemo() { const [o, setO] = React.useState(false); const { CommandPalette, Button } = DS; return <>
  <Button variant="secondary" onClick={() => setO(true)}>Open palette</Button><span style={mono}>or press ⌘K</span>
  <CommandPalette open={o} onOpen={() => setO(true)} onClose={() => setO(false)} items={[
    { label: 'New project', group: 'Actions', shortcut: '⌘N' }, { label: 'Invite teammate', group: 'Actions' }, { label: 'Open billing', group: 'Actions', shortcut: '⌘B' },
    { label: 'Anvil', description: 'Personal CRM · iOS', group: 'Projects' }, { label: 'Bellows', description: 'Backend · Go', group: 'Projects' }, { label: 'Sjocamp', description: 'Live · Web', group: 'Projects' },
    { label: 'Studio manual', group: 'Docs' }]} /></>; }
function TransitionDemo() { const [t, setT] = React.useState('Profile'); const { Tabs, PageTransition } = DS; const copy = { Profile: 'Name, email, and the studio you sign as.', Billing: 'Invoices, card, and plan. Paid monthly.', Team: 'Seven seats. Two pending invites.' };
  return <div style={{ display: 'flex', flexDirection: 'column', gap: 24, width: '100%' }}><Tabs tabs={Object.keys(copy)} value={t} onChange={setT} />
    <PageTransition transitionKey={t} variant="slideUp"><p style={{ margin: 0, fontSize: 17 }}>{copy[t]}</p></PageTransition></div>; }

const ROWS = [{"id":1,"name":"Anvil","client":"In-house","status":"Paid","amount":24000},{"id":2,"name":"Bellows","client":"Northwind","status":"Due","amount":18500},{"id":3,"name":"Cinder","client":"Halden Co.","status":"Failed","amount":9200},{"id":4,"name":"Plinth","client":"In-house","status":"Paid","amount":31000},{"id":5,"name":"Quench","client":"Arbor","status":"Due","amount":12750}];
const TCOLS = C => [
  { key: 'name', header: 'Project', sortable: true },
  { key: 'client', header: 'Client' },
  { key: 'status', header: 'Status', render: r => <C.Badge size="sm" variant={r.status === 'Paid' ? 'success' : r.status === 'Failed' ? 'error' : 'warning'}>{r.status}</C.Badge> },
  { key: 'amount', header: 'Amount', align: 'right', sortable: true, render: r => '$' + r.amount.toLocaleString('en-US') },
];
function App() {
  const { Button, ArrowLink, Eyebrow, Headline, Tag, StatusDot, Wordmark, Rule, Input, Select, Checkbox, Radio, Switch,
    Card, Stat, ProcessStep, Tabs, NavBar, Dialog, Toast, Tooltip } = DS;
  const [dlg, setDlg] = React.useState(false);
  const [toasts, setToasts] = React.useState([]);
  const [heat, setHeat] = React.useState(2);
  const [tab, setTab] = React.useState('All');
  const [stepAt, setStepAt] = React.useState(1);
  const C = DS;
  const pushToast = () => { const id = Date.now(); setToasts(t => [...t, id]); setTimeout(() => setToasts(t => t.filter(x => x !== id)), 4000); };

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '240px minmax(0,1fr)' }}>
      <Sidebar />
      <main style={{ padding: '64px 48px 128px', maxWidth: 1040, boxSizing: 'border-box' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 24, paddingBottom: 64 }}>
          <Eyebrow index="00">Design system</Eyebrow>
          <Headline size="display" lead="Sixty-six" accent="parts" style={{ fontSize: 96 }} />
          <p style={{ margin: 0, fontSize: 19, lineHeight: 1.55, color: 'var(--ink-2)', maxWidth: 620, textWrap: 'pretty' }}>
            Every primitive in the foundry, in every state. Soft rounded containers, full pills, 1px hairlines, one molten accent per surface.
          </p>
        </div>

        <Block id="button" index="01" name="Button" file="core/Button.jsx">
          <Spec label="Variants"><Button arrow>Start a project</Button><Button variant="secondary">Commission a piece</Button><Button variant="ghost" arrow>See the work</Button></Spec>
          <Spec label="Sizes"><Button size="sm">Small</Button><Button size="md">Medium</Button><Button size="lg" arrow>Large</Button></Spec>
          <Spec label="Disabled"><Button disabled>Primary</Button><Button variant="secondary" disabled>Secondary</Button></Spec>
          <Spec label="More"><Button variant="outline">Outline</Button><Button variant="destructive">Delete project</Button><Button loading>Saving</Button><Button variant="outline" icon="+" aria-label="Add" /><Button variant="ghost" icon={'\u2026'} aria-label="More" /></Spec>
          <Spec label="Full width" col><Button fullWidth arrow>Start a project</Button></Spec>
        </Block>

        <Block id="arrowlink" index="02" name="ArrowLink" file="core/ArrowLink.jsx">
          <Spec label="Default"><ArrowLink href="#">Read the studio journal</ArrowLink><ArrowLink href="#" arrow={'\u2198'}>Full-stack apps</ArrowLink></Spec>
        </Block>

        <Block id="eyebrow" index="03" name="Eyebrow" file="core/Eyebrow.jsx">
          <Spec label="Indexed"><Eyebrow index="01">The studio</Eyebrow><Eyebrow index="04">How we work</Eyebrow></Spec>
          <Spec label="Plain · ink"><Eyebrow>Studio archive · 2024–2026</Eyebrow><Eyebrow tone="ink">Identity v1.0 · MMXXVI</Eyebrow></Spec>
        </Block>

        <Block id="headline" index="04" name="Headline" file="core/Headline.jsx">
          <Spec label="Display" col><Headline size="display" lead="Software," accent="crafted in" after="precision" style={{ fontSize: 72 }} /></Spec>
          <Spec label="H2" col><Headline size="h2" lead="Heavy software," accent="quietly made" /></Spec>
          <Spec label="H3" col><Headline size="h3" lead="Products people" accent="pay for" /></Spec>
          <Spec label="H4" col><Headline size="h4" lead="Temper" /></Spec>
          <Spec label="Molten accent" col><Headline size="h3" lead="One mark, one sans," accent="one accent" moltenAccent period={false} /></Spec>
        </Block>

        <Block id="tag" index="05" name="Tag" file="core/Tag.jsx">
          <Spec label="Default">{['TypeScript', 'React', 'Postgres', 'Edge'].map(t => <Tag key={t}>{t}</Tag>)}</Spec>
          <Spec label="Ink"><Tag tone="ink">Swift</Tag><Tag tone="ink">SwiftUI</Tag></Spec>
        </Block>

        <Block id="statusdot" index="06" name="StatusDot" file="core/StatusDot.jsx">
          <Spec label="Status"><StatusDot status="live" /><StatusDot status="prototype" /><StatusDot status="archived" /></Spec>
          <Spec label="Custom label"><StatusDot status="live" label="Sjocamp · Live" /><StatusDot status="prototype" label="Meerkat · Prototype" /></Spec>
        </Block>

        <Block id="wordmark" index="07" name="Wordmark" file="core/Wordmark.jsx">
          <Spec label="Footer · 28"><Wordmark size="footer" /></Spec>
          <Spec label="Nav · 15"><Wordmark size="nav" /></Spec>
        </Block>

        <Block id="rule" index="08" name="Rule" file="core/Rule.jsx">
          <Spec label="Soft" col><Rule /></Spec>
          <Spec label="Ink" col><Rule tone="ink" /></Spec>
        </Block>

        <Block id="input" index="09" name="Input" file="forms/Input.jsx">
          <Spec label="States" col>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(240px,1fr))', gap: 24 }}>
              <Input label="Email" placeholder="you@studio.com" />
              <Input label="With hint" placeholder="Acme Inc." hint="As it appears on the invoice" />
              <Input label="Error" defaultValue="Under 10k" error="We start at 25k." />
            </div>
          </Spec>
          <Spec label="Multiline" col><Input label="The piece" multiline placeholder="What needs to exist, and why now?" /></Spec>
        </Block>

        <Block id="select" index="10" name="Select" file="forms/Select.jsx">
          <Spec label="Default" col><div style={{ maxWidth: 360 }}><Select label="Practice" options={['Full-stack apps', 'iOS apps', 'Backends', 'Agentic workflows', 'Design systems']} /></div></Spec>
        </Block>

        <Block id="checkbox" index="11" name="Checkbox" file="forms/Checkbox.jsx">
          <Spec label="States"><Checkbox label="Unchecked" /><Checkbox label="Checked" defaultChecked /><Checkbox label="Indeterminate" indeterminate /><Checkbox label="Disabled" disabled /></Spec>
          <Spec label="Detail"><Checkbox label="Send the journal" description="One email a month." /><Checkbox label="Accept the terms" error="Required." /><Checkbox size="lg" label="Large" /></Spec>
        </Block>

        <Block id="radio" index="12" name="Radio" file="forms/Radio.jsx">
          <Spec label="Row"><Radio options={['Web', 'iOS', 'Both']} direction="row" /></Spec>
          <Spec label="Column"><Radio options={['Under 3 months', '3–6 months', 'Ongoing']} /></Spec>
        </Block>

        <Block id="switch" index="13" name="Switch" file="forms/Switch.jsx">
          <Spec label="States"><Switch label="Off" /><Switch label="On" defaultChecked /><Switch label="Disabled" disabled /><Switch size="sm" label="Small" /><Switch size="lg" label="Large" /></Spec>
          <Spec label="Settings row" col><div style={{ maxWidth: 480 }}><Switch label="Weekly digest" description="One email, Fridays." labelPosition="left" style={{ width: '100%' }} /></div></Spec>
        </Block>

        <Block id="card" index="14" name="Card" file="display/Card.jsx">
          <Spec label="Variants" col>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(260px,1fr))', gap: 24 }}>
              <Card eyebrow="01 / 14" title="Anvil" accent="iOS" meta="Product · AI · iOS" footer={<span>{'\u2192'}</span>} href="#card">Personal CRM for people who hate CRMs. Voice notes in, structured contacts out.</Card>
              <Card eyebrow="Principle 01" title="Make it" accent="hold up in the hand">Software has weight, even when invisible. We never ship a tool that feels weightless.</Card>
              <Card title="Static, title only" />
            </div>
          </Spec>
        </Block>

        <Block id="stat" index="15" name="Stat" file="display/Stat.jsx">
          <Spec label="Row"><div style={{ display: 'flex', gap: 48, flexWrap: 'wrap' }}><Stat value="14" label="Pieces shipped" /><Stat value="3.2m" label="Daily users served" /><Stat value="100%" label="Independently held" /></div></Spec>
        </Block>

        <Block id="processstep" index="16" name="ProcessStep" file="display/ProcessStep.jsx">
          <Spec label="Heat pass" col>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 24 }}>
              {[['i', 'Brief', 'A short, written contract.'], ['ii', 'Cast', 'The first working artifact, rough but real.'], ['iii', 'Temper', 'Tight loops with real users.'], ['iv', 'Stamp', 'Ships with a signed manual.']].map(([n, t, b], i) =>
                <ProcessStep key={n} numeral={n} title={t} hot={i < heat}>{b}</ProcessStep>)}
            </div>
            <div style={{ display: 'flex', gap: 8 }}>{[0, 1, 2, 3, 4].map(i => <Button key={i} size="sm" variant={heat === i ? 'primary' : 'secondary'} onClick={() => setHeat(i)}>{i} hot</Button>)}</div>
          </Spec>
        </Block>

        <Block id="tabs" index="17" name="Tabs" file="navigation/Tabs.jsx">
          <Spec label="Line" col><Tabs tabs={['All', 'Product', 'Identity', 'Editorial']} value={tab} onChange={setTab} /><span style={mono}>Selected: {tab}</span></Spec>
          <Spec label="Pill"><Tabs variant="pill" tabs={[{ value: 'live', label: 'Live', count: 3 }, { value: 'proto', label: 'Prototypes', count: 2 }, { value: 'arch', label: 'Archived', disabled: true }]} /></Spec>
          <Spec label="Enclosed"><Tabs variant="enclosed" size="sm" tabs={['Day', 'Week', 'Month']} /></Spec>
        </Block>

        <Block id="navbar" index="18" name="NavBar" file="navigation/NavBar.jsx">
          <Spec label="Site header" col><div style={{ border: '1px solid var(--rule-soft)', minWidth: 0, overflow: 'hidden' }}><NavBar links={[{ label: 'Work', href: '#' }, { label: 'Capabilities', href: '#' }, { label: 'Studio', href: '#' }]} onCta={() => setDlg(true)} /></div></Spec>
        </Block>

        <Block id="dialog" index="19" name="Dialog" file="feedback/Dialog.jsx">
          <Spec label="Trigger"><Button arrow onClick={() => setDlg(true)}>Open dialog</Button><span style={mono}>Esc or scrim closes</span></Spec>
        </Block>

        <Block id="toast" index="20" name="Toast" file="feedback/Toast.jsx">
          <Spec label="Static" col>
            <Toast title="Brief received." meta="We reply within two days" onClose={() => {}} />
            <Toast title="Manual v1.2 stamped." meta="Neutral" status="neutral" />
            <Toast variant="success" title="Changes saved." />
            <Toast variant="warning" title="Card expires in 9 days." />
            <Toast variant="error" title="Payment failed." description="The card was declined." onClose={() => {}} />
          </Spec>
          <Spec label="Trigger"><Button variant="secondary" onClick={pushToast}>Show toast</Button></Spec>
        </Block>

        <Block id="tooltip" index="21" name="Tooltip" file="feedback/Tooltip.jsx">
          <Spec label="Placement">
            <Tooltip content="Ottawa · EST"><span style={{ ...mono, color: 'var(--ink)', borderBottom: '1px dashed var(--muted)' }}>Top</span></Tooltip>
            <Tooltip content="Established 2026" placement="bottom"><span style={{ ...mono, color: 'var(--ink)', borderBottom: '1px dashed var(--muted)' }}>Bottom</span></Tooltip>
            <Tooltip content="Left side" placement="left"><span style={{ ...mono, color: 'var(--ink)', borderBottom: '1px dashed var(--muted)' }}>Left</span></Tooltip>
            <Tooltip content="Right side, after a 300ms delay" placement="right" delay={300}><span style={{ ...mono, color: 'var(--ink)', borderBottom: '1px dashed var(--muted)' }}>Right</span></Tooltip>
          </Spec>
        </Block>

        <Block id="icon" index="22" name="Icon" file="core/Icon.jsx">
          <Spec label="Glyphs">{Object.keys(C.Icon.glyphs).map(n => <C.Tooltip key={n} content={n}><span style={{ width: 32, height: 32, display: 'grid', placeItems: 'center', border: '1px solid var(--rule-soft)' }}><C.Icon name={n} /></span></C.Tooltip>)}</Spec>
          <Spec label="Sizes">{['xs', 'sm', 'md', 'lg', 'xl', '2xl'].map(s => <C.Icon key={s} name="arrow-right" size={s} />)}</Spec>
          <Spec label="Colors">{['default', 'muted', 'quiet', 'primary'].map(c => <C.Icon key={c} name="dot" size="xl" color={c} />)}</Spec>
        </Block>
        <Block id="spinner" index="23" name="Spinner" file="core/Spinner.jsx">
          <Spec label="Sizes">{['xs', 'sm', 'md', 'lg', 'xl'].map(s => <C.Spinner key={s} size={s} />)}</Spec>
          <Spec label="Labelled"><C.Spinner size="sm" label="Casting build" /><C.Spinner size="sm" tone="muted" label="Muted" /></Spec>
          <Spec label="On ink"><span style={{ background: 'var(--ink)', padding: 16, display: 'inline-flex' }}><C.Spinner tone="paper" /></span></Spec>
        </Block>
        <Block id="buttongroup" index="24" name="ButtonGroup" file="core/ButtonGroup.jsx">
          <Spec label="Spaced"><C.ButtonGroup><C.Button variant="secondary">Cancel</C.Button><C.Button>Save changes</C.Button></C.ButtonGroup></Spec>
          <Spec label="Attached"><C.ButtonGroup attached><C.Button variant="ghost" size="sm" style={{ padding: '0 16px' }}>Day</C.Button><C.Button variant="ghost" size="sm" style={{ padding: '0 16px' }}>Week</C.Button><C.Button variant="ghost" size="sm" style={{ padding: '0 16px' }}>Month</C.Button></C.ButtonGroup>
            <C.ButtonGroup attached><C.Button size="sm" icon="B" aria-label="Bold" /><C.Button size="sm" icon={<em>I</em>} aria-label="Italic" /><C.Button size="sm" icon={<u>U</u>} aria-label="Underline" /></C.ButtonGroup></Spec>
          <Spec label="Vertical"><C.ButtonGroup vertical attached><C.Button variant="ghost" size="sm" style={{ padding: '0 24px' }}>Top</C.Button><C.Button variant="ghost" size="sm" style={{ padding: '0 24px' }}>Middle</C.Button><C.Button variant="ghost" size="sm" style={{ padding: '0 24px' }}>Bottom</C.Button></C.ButtonGroup></Spec>
          <Spec label="Full width" col><C.ButtonGroup fullWidth><C.Button variant="secondary">Back</C.Button><C.Button arrow>Continue</C.Button></C.ButtonGroup></Spec>
        </Block>
        <Block id="link" index="25" name="Link" file="core/Link.jsx">
          <Spec label="Variants"><C.Link href="#">Default</C.Link><C.Link href="#" variant="primary">Primary</C.Link><C.Link href="#" variant="muted">Muted</C.Link><C.Link href="#" external>External</C.Link><C.Link href="#" underline="always">Always underlined</C.Link></Spec>
          <Spec label="Inline" col><p style={{ margin: 0, fontSize: 17, maxWidth: 560 }}>Read the <C.Link href="#" underline="always">studio manual</C.Link> before you brief us. It covers ownership, timelines, and <C.Link href="#" variant="muted" underline="always">how we price</C.Link>.</p></Spec>
        </Block>
        <Block id="text" index="26" name="Text" file="core/Text.jsx">
          <Spec label="Scale" col>{['5xl', '4xl', '3xl', '2xl', 'xl', 'lg', 'md', 'sm', 'xs'].map(s => <C.Text key={s} size={s} color="heading">{s} · Heavy software, quietly made</C.Text>)}</Spec>
          <Spec label="Weights">{['normal', 'medium', 'semibold', 'bold'].map(w => <C.Text key={w} weight={w} color="heading">{w}</C.Text>)}</Spec>
          <Spec label="Colors">{['default', 'heading', 'muted', 'quiet', 'primary'].map(c => <C.Text key={c} color={c}>{c}</C.Text>)}</Spec>
          <Spec label="Styles"><C.Text mono>Mono label</C.Text><C.Text italic>Italic</C.Text><C.Text underline>Underline</C.Text><C.Text strike>Strike</C.Text><C.Text transform="uppercase">Uppercase</C.Text></Spec>
          <Spec label="Clamp" col><C.Text truncate style={{ maxWidth: 360 }}>Truncate · Go, Postgres, and Kafka on one AWS account, deployed from a single repository.</C.Text><C.Text lineClamp={2} style={{ maxWidth: 360 }}>Line clamp 2 · Go, Postgres, and Kafka on one AWS account, deployed from a single repository with a signed manual and a handover call.</C.Text></Spec>
          <Spec label="Headings" col>{[1, 2, 3, 4].map(n => <C.Text key={n} heading={n}>Heading {n}</C.Text>)}</Spec>
        </Block>
        <Block id="badge" index="27" name="Badge" file="core/Badge.jsx">
          <Spec label="Variants">{['default', 'primary', 'secondary', 'outline', 'success', 'warning', 'error'].map(v => <C.Badge key={v} variant={v}>{v}</C.Badge>)}</Spec>
          <Spec label="Sizes"><C.Badge size="sm">Small</C.Badge><C.Badge size="md">Medium</C.Badge><C.Badge size="lg">Large</C.Badge></Spec>
          <Spec label="Counts"><C.Badge variant="primary" count={3} /><C.Badge count={42} /><C.Badge variant="outline" count={128} /></Spec>
          <Spec label="Icons"><C.Badge dot>Dot</C.Badge><C.Badge leftIcon="↗">Up 12%</C.Badge><C.Badge variant="outline" rightIcon="→">Open</C.Badge></Spec>
        </Block>
        <Block id="avatar" index="28" name="Avatar" file="core/Avatar.jsx">
          <Spec label="Sizes">{['xs', 'sm', 'md', 'lg', 'xl', '2xl'].map(s => <C.Avatar key={s} size={s} name="Ada Lovelace" />)}</Spec>
          <Spec label="Fallbacks"><C.Avatar name="Grace" /><C.Avatar /><C.Avatar fallback="OF" /><C.Avatar src="data:image/png;base64,xx" name="Broken Image" /><C.Avatar name="Optimus Foundry" shape="square" /></Spec>
          <Spec label="In a tag"><C.Tag avatar={<C.Avatar name="Ada Lovelace" size={18} />}>Ada</C.Tag><C.Tag avatar={<C.Avatar name="Linus T" size={18} />} onRemove={() => {}}>Linus</C.Tag></Spec>
        </Block>
        <Block id="skeleton" index="29" name="Skeleton" file="core/Skeleton.jsx">
          <Spec label="Shapes"><C.Skeleton variant="circular" width={48} /><C.Skeleton variant="rounded" width={120} /><C.Skeleton variant="rectangular" width={200} height={80} /></Spec>
          <Spec label="Card" col><div style={{ border: '1px solid var(--rule-soft)', padding: 32, display: 'flex', flexDirection: 'column', gap: 16, maxWidth: 360 }}><C.Skeleton width={80} height={10} /><C.Skeleton height={24} width="70%" /><C.Skeleton lines={3} /></div></Spec>
        </Block>

        <Block id="label" index="30" name="Label" file="forms/Label.jsx">
          <Spec label="Variants" col><div style={{ display: 'flex', flexDirection: 'column', gap: 24, maxWidth: 420 }}>
            <C.Label required>Email</C.Label><C.Label subText="Shown on invoices." badge={<C.Badge size="sm" variant="secondary">Optional</C.Badge>}>Company</C.Label>
            <C.Label action={<C.Link href="#" size="sm" variant="muted">Forgot?</C.Link>}>Password</C.Label><C.Label disabled>Disabled</C.Label></div></Spec>
        </Block>
        <Block id="formhint" index="31" name="FormHint" file="forms/FormHint.jsx">
          <Spec label="Variants" col><C.FormHint>As it appears on the invoice.</C.FormHint><C.FormHint icon>With the info glyph.</C.FormHint><C.FormHint variant="error">We start at 25k.</C.FormHint><C.FormHint variant="success">Domain verified.</C.FormHint></Spec>
        </Block>
        <Block id="formfield" index="32" name="FormField" file="forms/FormField.jsx">
          <Spec label="Wrapping" col><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(240px,1fr))', gap: 24 }}>
            <C.FormField label="Practice" helperText="Pick the closest fit."><C.Dropdown fullWidth options={['Full-stack apps', 'iOS apps', 'Backends']} /></C.FormField>
            <C.FormField label="Seats" required error="At least one seat."><C.Stepper min={0} defaultValue={0} label="Seats" /></C.FormField>
            <C.FormField label="Notes"><textarea rows={3} style={{ fontFamily: 'var(--font-sans)', fontSize: 15, border: '1px solid var(--rule-soft)', padding: 12, outline: 'none' }} /></C.FormField></div></Spec>
        </Block>
        <Block id="textfield" index="33" name="TextField" file="forms/TextField.jsx">
          <Spec label="States" col><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(240px,1fr))', gap: 24 }}>
            <C.TextField label="Email" type="email" placeholder="you@studio.com" required helperText="We reply within two days." />
            <C.TextField label="Search" leftIcon="/" placeholder="Search projects" />
            <C.TextField label="Password" type="password" defaultValue="hunter22" rightIcon={<C.Icon name="check" />} />
            <C.TextField label="Budget" defaultValue="Under 10k" error="We start at 25k." />
            <C.TextField label="Filled" variant="filled" placeholder="Filled variant" />
            <C.TextField label="Disabled" disabled defaultValue="Read only" /></div></Spec>
          <Spec label="Sizes" col><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 24, alignItems: 'end' }}><C.TextField size="sm" label="Small" placeholder="36px" /><C.TextField label="Medium" placeholder="48px" /><C.TextField size="lg" label="Large" placeholder="56px" /></div></Spec>
        </Block>
        <Block id="textarea" index="34" name="TextArea" file="forms/TextArea.jsx">
          <Spec label="States" col><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(280px,1fr))', gap: 24 }}>
            <C.TextArea label="The piece" required placeholder="What needs to exist, and why now?" helperText="Two or three sentences is plenty." />
            <C.TextArea label="Notes" rows={4} resize="none" maxLength={280} defaultValue="Ship before the Q1 board meeting." />
            <C.TextArea label="Error" error="Tell us a little more." /></div></Spec>
        </Block>
        <Block id="dropdown" index="35" name="Dropdown" file="forms/Dropdown.jsx">
          <Spec label="Variants"><C.Dropdown label="Practice" placeholder="Pick one" options={[{ value: 'web', label: 'Full-stack apps', description: 'Go, Postgres, React' }, { value: 'ios', label: 'iOS apps', description: 'Swift, SwiftUI' }, { divider: true }, { value: 'agents', label: 'Agentic workflows' }, { value: 'ds', label: 'Design systems', disabled: true }]} />
            <C.Dropdown label="Filled" variant="filled" defaultValue="Weekly" options={['Daily', 'Weekly', 'Monthly']} /><C.Dropdown label="Small" size="sm" options={['Ottawa', 'Toronto', 'Remote']} /><C.Dropdown label="Error" error="Pick a region." options={['ca-central-1', 'us-east-1']} /><C.Dropdown label="Disabled" disabled options={['Locked']} defaultValue="Locked" /></Spec>
        </Block>
        <Block id="multiselect" index="36" name="MultiSelect" file="forms/MultiSelect.jsx">
          <Spec label="Default"><C.MultiSelect label="Stack" defaultValue={['go', 'pg']} options={[{ value: 'go', label: 'Go' }, { value: 'pg', label: 'Postgres' }, { value: 'kafka', label: 'Kafka' }, { value: 'swift', label: 'Swift', description: 'iOS only' }, { divider: true }, { value: 'php', label: 'PHP', disabled: true }]} />
            <C.MultiSelect label="Many items" maxDisplay={2} options={['Ottawa', 'Toronto', 'Montréal', 'Vancouver', 'Calgary', 'Halifax', 'Winnipeg', 'Québec', 'Victoria', 'Regina']} defaultValue={['Ottawa', 'Toronto', 'Montréal']} /></Spec>
        </Block>
        <Block id="slider" index="37" name="Slider" file="forms/Slider.jsx">
          <Spec label="Variants" col><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(240px,1fr))', gap: 32 }}>
            <C.Slider label="Budget" defaultValue={40} formatValue={v => v + 'k'} /><C.Slider label="Retention" min={7} max={90} step={7} defaultValue={28} formatValue={v => v + ' days'} />
            <C.Slider size="sm" label="Small" defaultValue={20} /><C.Slider size="lg" label="Large" defaultValue={70} /><C.Slider label="Disabled" disabled defaultValue={50} /></div></Spec>
        </Block>
        <Block id="stepper" index="38" name="Stepper" file="forms/Stepper.jsx">
          <Spec label="Sizes"><C.Stepper size="sm" defaultValue={1} min={1} label="Small" /><C.Stepper defaultValue={2} min={1} max={10} label="Seats" /><C.Stepper size="lg" defaultValue={5} step={5} label="Large" /><C.Stepper disabled defaultValue={3} label="Disabled" /></Spec>
        </Block>
        <Block id="datepicker" index="39" name="DatePicker" file="forms/DatePicker.jsx">
          <Spec label="Variants" col><div style={{ display: 'flex', gap: 24, flexWrap: 'wrap', minHeight: 60 }}>
            <C.DatePicker label="Launch" /><C.DatePicker label="With value" defaultValue={new Date(2026, 9, 21)} /><C.DatePicker label="Future only · Mon first" min={new Date()} weekStartsOn={1} />
            <C.DatePicker label="ISO format" size="sm" format={d => d.toISOString().slice(0, 10)} defaultValue={new Date(2026, 11, 1)} /><C.DatePicker label="Disabled" disabled /></div></Spec>
        </Block>
        <Block id="fileupload" index="40" name="FileUpload" file="forms/FileUpload.jsx">
          <Spec label="Dropzone" col><C.FileUpload label="Attachments" accept=".pdf,.png,.jpg" maxSize={5 * 1048576} maxFiles={4} simulateUpload defaultFiles={[{ name: 'brief-v2.pdf', size: 482000 }, { name: 'wireframes.png', size: 1240000, progress: 64 }, { name: 'archive.zip', size: 18000000, error: 'Over 5.0 MB limit' }]} /></Spec>
          <Spec label="Button"><C.FileUpload variant="button" multiple={false} accept="image/*" buttonLabel="Upload logo" /></Spec>
          <Spec label="Disabled" col><C.FileUpload disabled /></Spec>
        </Block>

        <Block id="accordion" index="41" name="Accordion" file="display/Accordion.jsx">
          <Spec label="Single" col><C.Accordion defaultExpanded={['own']} items={[{ id: 'own', title: 'Who owns the code?', content: 'You do. We hand over the repository, the keys, and the manual on the last day.' }, { id: 'time', title: 'How long does a piece take?', description: 'Typical ranges', content: 'Six to fourteen weeks for a first version. Retainers run monthly after that.' }, { id: 'tools', title: 'What do you build with?', icon: '/', content: 'Go, Postgres, and Kafka on the backend. React on the web. Swift and SwiftUI on iOS.' }, { id: 'nope', title: 'Do you take equity?', disabled: true, content: '' }]} /></Spec>
          <Spec label="Multiple" col><C.Accordion multiple defaultExpanded={[0, 1]} items={[{ title: 'Brief', content: 'A short, written contract.' }, { title: 'Cast', content: 'The first working artifact, rough but real.' }, { title: 'Temper', content: 'Tight loops with real users.' }]} /></Spec>
        </Block>
        <Block id="statcard" index="42" name="StatCard" file="data/StatCard.jsx">
          <Spec label="Variants" col><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(200px,1fr))', gap: 16 }}>
            <C.StatCard label="MRR" value={48200} format={v => '$' + Math.round(v).toLocaleString()} delta={12.4} period="vs Sep" animate />
            <C.StatCard label="Churn" value="2.1%" delta={-0.3} variant="filled" />
            <C.StatCard label="Builds" value={1284} icon="↗" previousValue={1170} />
            <C.StatCard label="Uptime" value="99.98%" delta="0.00%" trend="neutral" variant="plain" />
            <C.StatCard label="Open invoices" value={6} onClick={() => {}} period="Click to view" /></div></Spec>
        </Block>
        <Block id="emptystate" index="43" name="EmptyState" file="data/EmptyState.jsx">
          <Spec label="Sizes" col><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(280px,1fr))', gap: 24 }}>
            <C.EmptyState bordered title="No projects" accent="yet" description="Cast your first piece and it shows up here." actions={<><C.Button size="sm" arrow>New project</C.Button><C.Button size="sm" variant="ghost">Import</C.Button></>} />
            <C.EmptyState bordered size="sm" icon="?" title="Nothing matches" description="Try fewer filters." actions={<C.Button size="sm" variant="secondary">Clear filters</C.Button>} />
            <C.EmptyState bordered size="sm" icon={null} align="start" eyebrow="Inbox" title="All read" /></div></Spec>
        </Block>
        <Block id="filtertabs" index="44" name="FilterTabs" file="data/FilterTabs.jsx">
          <Spec label="Default"><C.FilterTabs items={[{ value: 'all', label: 'All', count: 14 }, { value: 'live', label: 'Live', count: 3 }, { value: 'proto', label: 'Prototypes', count: 2 }, { value: 'arch', label: 'Archived', count: 9 }]} /></Spec>
          <Spec label="Small · no counts"><C.FilterTabs size="sm" showCounts={false} items={['Day', 'Week', 'Month', 'Year']} /></Spec>
        </Block>
        <Block id="list" index="45" name="List" file="data/List.jsx">
          <Spec label="Default" col><C.List items={[{ primary: 'Sjocamp', secondary: 'Booking for summer camps', leading: <C.Avatar name="Sjo Camp" size="sm" />, trailing: <C.StatusDot status="live" /> }, { primary: 'Meerkat', secondary: 'Agentic QA for web apps', leading: <C.Avatar name="Meer Kat" size="sm" />, trailing: <C.StatusDot status="prototype" /> }, { primary: 'TickUpToks', secondary: 'Short-form scheduling', leading: <C.Avatar name="Tick Up" size="sm" />, trailing: 'Archived' }]} /></Spec>
          <Spec label="Interactive" col><C.List items={[{ primary: 'Profile', href: '#' }, { primary: 'Billing', secondary: 'Visa ending 4242', href: '#' }, { primary: 'Danger zone', disabled: true, onClick: () => {} }]} /></Spec>
          <Spec label="Grouped · bordered" col><C.List bordered size="sm" groups={[{ label: 'Today', items: [{ primary: 'Build 14 shipped', trailing: '14:02' }, { primary: 'Ada joined', trailing: '09:40' }] }, { label: 'Yesterday', items: [{ primary: 'Invoice 0031 paid', trailing: '16:15' }] }]} /></Spec>
        </Block>
        <Block id="table" index="46" name="Table" file="data/Table.jsx">
          <Spec label="Full" col><C.Table caption="Invoices · Q4" selectable defaultSort={{ key: 'amount', dir: 'desc' }} renderExpanded={r => r.client + ' · net 30 · issued Oct 1'} columns={TCOLS(C)} data={ROWS} /></Spec>
          <Spec label="Striped · sm" col><C.Table size="sm" striped columns={TCOLS(C)} data={ROWS.slice(0, 3)} /></Spec>
          <Spec label="Bordered" col><C.Table bordered columns={TCOLS(C)} data={ROWS.slice(0, 2)} /></Spec>
          <Spec label="Loading" col><C.Table loading loadingRows={3} columns={TCOLS(C)} data={[]} /></Spec>
        </Block>
        <Block id="datagrid" index="47" name="DataGrid" file="data/DataGrid.jsx">
          <Spec label="Full featured" col><C.DataGrid title="Invoices" searchable selectable pageSize={3} columns={TCOLS(C)} data={ROWS} actions={<C.Button size="sm" arrow>New invoice</C.Button>} /></Spec>
          <Spec label="Empty" col><C.DataGrid title="Builds" columns={TCOLS(C)} data={[]} emptyDescription="Builds appear after the first cast." emptyActions={<C.Button size="sm" arrow>Cast a build</C.Button>} /></Spec>
        </Block>

        <Block id="breadcrumb" index="48" name="Breadcrumb" file="navigation/Breadcrumb.jsx">
          <Spec label="Default"><C.Breadcrumb items={[{ label: 'Studio', href: '#' }, { label: 'Work', href: '#' }, { label: 'Anvil' }]} /></Spec>
          <Spec label="Collapsed"><C.Breadcrumb maxItems={3} items={[{ label: 'Studio', href: '#' }, { label: 'Work', href: '#' }, { label: 'iOS', href: '#' }, { label: 'Anvil', href: '#' }, { label: 'Build 14' }]} /></Spec>
          <Spec label="Separator · sizes"><C.Breadcrumb size="sm" separator="·" items={[{ label: 'Settings', href: '#' }, { label: 'Billing' }]} /><C.Breadcrumb size="lg" separator="→" items={[{ label: 'Docs', href: '#' }, { label: 'Manual' }]} /></Spec>
        </Block>
        <Block id="pagination" index="49" name="Pagination" file="navigation/Pagination.jsx">
          <Spec label="Variants" col><C.Pagination total={20} defaultPage={6} /><C.Pagination total={20} defaultPage={6} variant="outline" /><C.Pagination total={5} defaultPage={2} variant="ghost" showFirstLast={false} /></Spec>
          <Spec label="Sizes" col><C.Pagination size="sm" total={8} /><C.Pagination size="lg" total={8} siblings={2} /><C.Pagination total={8} disabled /></Spec>
        </Block>
        <Block id="stepindicator" index="50" name="StepIndicator" file="navigation/StepIndicator.jsx">
          <Spec label="Horizontal" col><C.StepIndicator current={stepAt} onStepClick={setStepAt} steps={[{ label: 'Brief', description: 'Written contract' }, { label: 'Cast', description: 'First artifact' }, { label: 'Temper', description: 'Real users' }, { label: 'Stamp', description: 'Signed manual' }]} />
            <div style={{ display: 'flex', gap: 8 }}>{[0, 1, 2, 3, 4].map(i => <C.Button key={i} size="sm" variant={stepAt === i ? 'primary' : 'secondary'} onClick={() => setStepAt(i)}>{i === 4 ? 'Done' : 'Step ' + (i + 1)}</C.Button>)}</div></Spec>
          <Spec label="Vertical · error" col><C.StepIndicator orientation="vertical" numerals="arabic" current={1} steps={[{ label: 'Account', description: 'Email and password' }, { label: 'Billing', description: 'Card was declined', status: 'error' }, { label: 'Review' }]} /></Spec>
          <Spec label="Sizes" col><C.StepIndicator size="sm" current={1} steps={[{ label: 'Cart' }, { label: 'Shipping' }, { label: 'Pay' }]} /><C.StepIndicator size="lg" current={2} steps={[{ label: 'Cart' }, { label: 'Shipping' }, { label: 'Pay' }]} /></Spec>
        </Block>
        <Block id="sidebar" index="51" name="Sidebar" file="navigation/Sidebar.jsx">
          <Spec label="Groups" col><div style={{ display: 'flex', gap: 24, alignItems: 'stretch', height: 420, border: '1px solid var(--rule-soft)', overflow: 'auto', minWidth: 0 }}>
            <C.Sidebar collapsible header={<C.Wordmark size="nav" />} defaultValue="Overview" footer={<div style={{ display: 'flex', gap: 12, alignItems: 'center', padding: '0 12px' }}><C.Avatar name="Ada Lovelace" size="sm" /><C.Text size="sm" color="heading">Ada Lovelace</C.Text></div>}
              groups={[{ label: 'Workspace', items: [{ label: 'Overview', icon: '·' }, { label: 'Projects', icon: '/', badge: 14 }, { label: 'Builds', icon: '↗' }] }, { label: 'Account', items: [{ label: 'Billing', icon: '$' }, { label: 'Team', icon: '+', badge: 7 }, { label: 'Audit log', icon: '…', disabled: true }] }]} />
            <C.Sidebar compact dividers defaultValue="Profile" width={200} groups={[{ items: [{ label: 'Profile' }, { label: 'Security' }] }, { items: [{ label: 'Billing' }, { label: 'Invoices' }] }]} />
            <C.Sidebar defaultCollapsed defaultValue="Overview" items={[{ label: 'Overview' }, { label: 'Projects' }, { label: 'Builds' }, { label: 'Billing' }]} /></div></Spec>
        </Block>
        <Block id="commandpalette" index="52" name="CommandPalette" file="navigation/CommandPalette.jsx">
          <Spec label="Trigger"><PaletteDemo /></Spec>
        </Block>

        <Block id="alert" index="53" name="Alert" file="feedback/Alert.jsx">
          <Spec label="Variants" col>
            <C.Alert title="Brief received.">We reply within two days.</C.Alert>
            <C.Alert variant="success" title="Manual v1.2 stamped." />
            <C.Alert variant="warning" title="Card expires in 9 days." action={<C.ArrowLink href="#">Update card</C.ArrowLink>} />
            <C.Alert variant="error" title="Deploy failed." onDismiss={() => {}}>Postgres refused the migration. Nothing shipped.</C.Alert>
            <C.Alert icon={false}>No icon, no title. One plain sentence.</C.Alert></Spec>
        </Block>
        <Block id="banner" index="54" name="Banner" file="feedback/Banner.jsx">
          <Spec label="Variants" col>
            <C.Banner title="Scheduled maintenance.">Sunday 02:00–03:00 EST. Reads stay up.</C.Banner>
            <C.Banner variant="ink" status="warning" title="Trial ends in 3 days." action={<C.Button size="sm" variant="secondary" style={{ color: 'var(--paper)', borderColor: 'var(--paper)' }}>Pick a plan</C.Button>} />
            <C.Banner variant="outline" status="success" title="Payments are back." >Stripe recovered at 14:02.</C.Banner>
            <C.Banner variant="outline" title="We use one cookie." dismissible={false} action={<C.Button size="sm">Fine</C.Button>}>It keeps you signed in.</C.Banner></Spec>
        </Block>
        <Block id="progress" index="55" name="Progress" file="feedback/Progress.jsx">
          <Spec label="Variants" col><div style={{ display: 'flex', flexDirection: 'column', gap: 24, maxWidth: 560 }}>
            <C.Progress value={64} label="Importing contacts.csv" showValue />
            <C.Progress indeterminate label="Casting build" />
            <C.Progress value={100} variant="success" label="Upload" showValue />
            <C.Progress value={88} variant="warning" label="Storage" showValue />
            <C.Progress value={30} variant="error" label="Failed at row 412" showValue />
            <C.Progress value={2} max={4} variant="heat" size="sm" label="Heat pass · ii of iv" /></div></Spec>
          <Spec label="Sizes" col><div style={{ display: 'flex', flexDirection: 'column', gap: 16, maxWidth: 560 }}><C.Progress size="sm" value={40} /><C.Progress size="md" value={60} /><C.Progress size="lg" value={80} /></div></Spec>
        </Block>

        <Block id="drawer" index="56" name="Drawer" file="overlays/Drawer.jsx">
          <Spec label="Trigger"><DrawerDemo /><span style={mono}>Esc or scrim closes</span></Spec>
        </Block>
        <Block id="popover" index="57" name="Popover" file="overlays/Popover.jsx">
          <Spec label="Placements"><div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', padding: '8px 0' }}>{['top', 'bottom', 'left', 'right'].map(p => <C.Popover key={p} placement={p} trigger={<C.Button size="sm" variant="secondary">{p}</C.Button>} title="Share this build" width={240}>Anyone with the link can view build 14.</C.Popover>)}</div></Spec>
          <Spec label="Rich"><C.Popover align="start" trigger={<C.Button size="sm" variant="outline" icon="?" aria-label="Help" />} title="What is a heat pass?" width={320}><span>The molten rail that moves across the four steps of our process, one at a time.</span><C.ArrowLink href="#">Read the manual</C.ArrowLink></C.Popover></Spec>
        </Block>
        <Block id="dropdownmenu" index="58" name="DropdownMenu" file="overlays/DropdownMenu.jsx">
          <Spec label="Menus"><C.DropdownMenu trigger={<C.Button size="sm" variant="secondary" rightIcon="↓">File</C.Button>} items={[{ label: 'New project', shortcut: '⌘N' }, { label: 'Open…', shortcut: '⌘O' }, { divider: true }, { group: 'Export' }, { label: 'PDF', sublabel: 'Print-ready' }, { label: 'Markdown' }, { divider: true }, { label: 'Delete', danger: true, shortcut: '⌫' }]} />
            <C.DropdownMenu trigger={<C.Button size="sm" variant="secondary" rightIcon="↓">View</C.Button>} items={[{ label: 'Show grid', checked: true }, { label: 'Show rulers', checked: false }, { label: 'Compact rows', checked: true }]} caption="Saved per project" />
            <C.DropdownMenu align="end" width={260} trigger={<span style={{ cursor: 'pointer' }}><C.Avatar name="Ada Lovelace" size="sm" /></span>} header={<div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}><C.Text size="sm" weight="semibold" color="heading">Ada Lovelace</C.Text><C.Text mono>ada@optimusfoundry.com</C.Text></div>} items={[{ label: 'Profile', active: true }, { label: 'Billing' }, { label: 'Sign out' }]} /></Spec>
          <Spec label="Context menu" col><C.DropdownMenu contextMenu items={[{ label: 'Copy link' }, { label: 'Duplicate' }, { divider: true }, { label: 'Archive', danger: true }]}><div style={{ padding: 40, border: '1px dashed var(--muted-2)', textAlign: 'center', ...mono }}>Right-click here</div></C.DropdownMenu></Spec>
        </Block>

        <Block id="container" index="59" name="Container" file="layout/Container.jsx">
          <Spec label="Sizes" col>{['sm', 'md', 'lg'].map(s => <C.Container key={s} size={s} padded={false} style={{ background: 'var(--paper-2)', padding: 12, ...mono }}>{s}</C.Container>)}</Spec>
        </Block>
        <Block id="stack" index="60" name="Stack" file="layout/Stack.jsx">
          <Spec label="Gaps" col>{['xs', 'sm', 'md', 'lg'].map(g => <C.Stack key={g} direction="row" gap={g} align="center"><span style={{ ...mono, width: 32 }}>{g}</span>{[1, 2, 3, 4].map(i => <span key={i} style={{ width: 32, height: 32, background: 'var(--paper-2)', border: '1px solid var(--rule-soft)' }} />)}</C.Stack>)}</Spec>
          <Spec label="Navbar" col><C.Stack direction="row" justify="space-between" align="center" style={{ borderBottom: '1px solid var(--rule-soft)', paddingBottom: 16 }}><C.Wordmark size="nav" /><C.Stack direction="row" gap="lg"><C.Link href="#">Work</C.Link><C.Link href="#">Studio</C.Link></C.Stack><C.Button size="sm" arrow>Start</C.Button></C.Stack></Spec>
        </Block>
        <Block id="grid" index="61" name="Grid" file="layout/Grid.jsx">
          <Spec label="Columns" col><C.Grid columns={4} gap="sm">{[1, 2, 3, 4, 5, 6, 7, 8].map(i => <div key={i} style={{ height: 48, background: 'var(--paper-2)', display: 'grid', placeItems: 'center', ...mono }}>{String(i).padStart(2, '0')}</div>)}</C.Grid></Spec>
          <Spec label="Auto-fit" col><C.Grid minChildWidth={200} gap="md" animated>{['Anvil', 'Bellows', 'Cinder', 'Plinth'].map(n => <C.Card key={n} title={n} meta="Product" />)}</C.Grid></Spec>
        </Block>
        <Block id="aspectratio" index="62" name="AspectRatio" file="layout/AspectRatio.jsx">
          <Spec label="Presets" col><C.Grid columns={5} gap="sm" align="start">{['square', 'video', 'portrait', 'photo', 'wide'].map(r => <C.AspectRatio key={r} ratio={r} />)}</C.Grid></Spec>
          <Spec label="Placeholder" col><div style={{ maxWidth: 480 }}><C.AspectRatio ratio="video" label="Product shot · Anvil contact view" /></div></Spec>
        </Block>
        <Block id="pagehero" index="63" name="PageHero" file="layout/PageHero.jsx">
          <Spec label="Large" col><C.PageHero index="02" eyebrow="Work" title="Fourteen pieces," accent="all still running" description="Every project we have shipped since MMXXIV, what it runs on, and who owns it now." actions={<><C.Button arrow>Start a project</C.Button><C.ArrowLink href="#">Read the manual</C.ArrowLink></>} style={{ padding: '32px 0' }} /></Spec>
          <Spec label="App" col><C.PageHero size="md" title="Good morning," accent="Ada" description="Three builds shipped overnight." actions={<C.Button size="sm" arrow>New project</C.Button>} ruled={false} style={{ padding: 0 }} /></Spec>
        </Block>
        <Block id="sectionheader" index="64" name="SectionHeader" file="layout/SectionHeader.jsx">
          <Spec label="Medium" col><C.SectionHeader index="01" eyebrow="The studio" title="Heavy software," accent="quietly made" description="We cast our own SaaS and mobile apps, and take a few commissions a year." actions={<C.ArrowLink href="#">About the studio</C.ArrowLink>} /></Spec>
          <Spec label="Small · h3" col><C.SectionHeader size="sm" as="h3" title="At a" accent="glance" actions={<C.ArrowLink href="#">All metrics</C.ArrowLink>} /></Spec>
        </Block>
        <Block id="pageshell" index="65" name="PageShell" file="layout/PageShell.jsx">
          <Spec label="Layouts" col>{['half', 'third', 'sidebar'].map(l => <div key={l} style={{ border: '1px solid var(--rule-soft)', paddingTop: 24 }}><C.PageShell layout={l} gap={16} style={{ paddingBottom: 24 }} header={<span style={mono}>{l}</span>}>{(l === 'third' ? [1, 2, 3] : [1, 2]).map(i => <div key={i} style={{ height: 64, background: 'var(--paper-2)' }} />)}</C.PageShell></div>)}</Spec>
        </Block>
        <Block id="pagetransition" index="66" name="PageTransition" file="layout/PageTransition.jsx">
          <Spec label="Tabs" col><TransitionDemo /></Spec>
        </Block>
      </main>

      <Dialog open={dlg} onClose={() => setDlg(false)} eyebrow="05 Get in touch" title="Commission a" accent="piece"
        actions={<><Button variant="secondary" onClick={() => setDlg(false)}>Cancel</Button><Button arrow onClick={() => { setDlg(false); pushToast(); }}>Send brief</Button></>}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
          <Input label="Email" placeholder="you@studio.com" />
          <Input label="The piece" multiline placeholder="What needs to exist?" />
        </div>
      </Dialog>
      <div style={{ position: 'fixed', right: 32, bottom: 32, display: 'flex', flexDirection: 'column', gap: 8, zIndex: 200 }}>
        {toasts.map(id => <Toast key={id} title="Brief received." meta="We reply within two days" onClose={() => setToasts(t => t.filter(x => x !== id))} />)}
      </div>
    </div>
  );
}

export default App;
