// Generates src/styles/tokens.generated.ts from the compiled SCSS: `TokenName`, every --q-* custom
// property quiet declares, and `cssVar()`. Token names stay readable strings in TS (searchable
// next to the SCSS); the type makes a typo or a renamed token a type error, and
// scripts/check-tokens.mjs validates the strings tsc can't see (style objects, CSS text).
import { globSync, writeFileSync } from "node:fs";
import { basename } from "node:path";
import { initCompiler } from "sass-embedded";

export const OUT = "src/styles/tokens.generated.ts";
// The same list as JSON, shipped as dist/tokens.json for the quiet/known-tokens Stylelint rule.
export const LIST = "src/styles/tokens.generated.json";
const DECL = /(--q-[a-z0-9-]+)\s*:/g;

/** Every --q-* name declared by quiet's stylesheets, sorted. */
export function tokenNames() {
	const compiler = initCompiler();
	const names = new Set();
	const files = [
		"src/styles/index.scss",
		...globSync("src/components/**/*.scss").filter((f) => !basename(f).startsWith("_")),
	];
	for (const f of files) for (const m of compiler.compile(f).css.matchAll(DECL)) names.add(m[1]);
	compiler.dispose();
	return [...names].sort();
}

/** The generated file's text, compiled from the current SCSS. */
export function renderTokens(names = tokenNames()) {
	return `// GENERATED by scripts/gen-tokens.mjs from src/styles and src/components SCSS — do not edit.

/** Every --q-* custom property quiet declares (palette, semantic and component tiers). */
export type TokenName =\n${names.map((n) => `\t| ${JSON.stringify(n)}`).join("\n")};

/** A token as a CSS value, checked against the SCSS: \`cssVar("--q-space-stack")\`. */
export function cssVar<N extends TokenName>(name: N): \`var(\${N})\` {
\treturn \`var(\${name})\`;
}
`;
}

export const renderList = (names = tokenNames()) => `${JSON.stringify(names, null, "\t")}\n`;

export function genTokens() {
	const names = tokenNames();
	writeFileSync(OUT, renderTokens(names));
	writeFileSync(LIST, renderList(names));
	return names.length;
}
