// Generates the parts of quiet that are derived mechanically from the Optimus Foundry mirror
// (docs/reference/optimus-design), so they can never drift by hand:
//   src/index.ts                         — one export per component, in ds-loader.js order
//   src/styles/tokens.generated.ts      — the TokenName type (scripts/gen-tokens.mjs)
//   src/stories/catalog.generated.tsx    — the App from components/index.html, verbatim (untyped)
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { genTokens } from "./gen-tokens.mjs";

const REF = "docs/reference/optimus-design";
const HEADER =
	"// GENERATED by scripts/gen.mjs from docs/reference/optimus-design — do not edit.\n";

const loader = readFileSync(`${REF}/ds-loader.js`, "utf8");
const files = JSON.parse(loader.match(/var FILES = (\[[^\]]*\])/)[1]);
// quiet's own components (not in the reference), appended after the reference ones:
// src/components/future — the Claude Design "Future Components" concepts, rebuilt on quiet tokens;
// src/components/charts — quiet's chart set; src/components/chat — AI chat (thread, messages, composer).
const own = ["future", "charts", "chat"]
	.flatMap((group) =>
		readdirSync(`src/components/${group}`)
			.filter((f) => f.endsWith(".tsx"))
			.map((f) => `${group}/${f.slice(0, -4)}`)
			.sort(),
	)
	.concat(["feedback/Toaster"]);
writeFileSync(
	"src/index.ts",
	`${HEADER}// Styles first: the @layer order statement must be the first CSS in every bundle (a minifier\n// otherwise drops it and layers rank by first appearance, with q.components above q.base).\nimport "./styles/index.scss";\n${[
		...files,
		...own,
	]
		.map((f) => `export * from "./components/${f}";`)
		.join(
			"\n",
		)}\nexport { QuietRoot, type QuietRootProps } from "./QuietRoot";\nexport { applyTheme, type BuiltInTheme, defaultTheme, defineThemes, getTheme, resolveTheme, type ThemeDefinition, type ThemeName, themeNames, themes } from "./styles/themes/themes";\nexport { ThemeProvider, useTheme } from "./styles/themes/ThemeProvider";\nexport { type LinkComponent, type LinkComponentProps, useLinkComponent } from "./lib/link";\nexport { cssVar, type TokenName } from "./styles/tokens.generated";\n`,
);

const html = readFileSync(`${REF}/components/index.html`, "utf8");
const script = html.match(/<script type="text\/babel">\n([\s\S]*)<\/script>/)[1];
const boot =
	/let DS;\nloadDS\('\.\.\/'\)\.then\(d => \{ DS = d; ReactDOM\.createRoot\(document\.getElementById\('root'\)\)\.render\(<App \/>\); \}\);\n$/;
if (!boot.test(script)) throw new Error("index.html boot line changed — update gen.mjs");
// The App is the reference's untyped Babel script, kept verbatim so the catalog stays
// pixel-identical to it; it is checked by tests/parity.spec.ts, not by tsc.
writeFileSync(
	"src/stories/catalog.generated.tsx",
	`${HEADER}// @ts-nocheck\nimport React from "react";\nimport * as DS from "../index";\n\n${script.replace(boot, "")}\nexport default App;\n`,
);
const tokenCount = genTokens();
console.log(
	`index.ts: ${files.length} components; catalog: ${script.split("\n").length} lines; ${tokenCount} tokens`,
);
