// Generates the parts of quiet that are derived mechanically from the Optimus Foundry mirror
// (docs/reference/optimus-design), so they can never drift by hand:
//   src/index.ts                         — one export per component, in ds-loader.js order
//   src/stories/catalog.generated.jsx    — the App from components/index.html, verbatim
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const REF = "docs/reference/optimus-design";
const HEADER =
	"// GENERATED by scripts/gen.mjs from docs/reference/optimus-design — do not edit.\n";

const loader = readFileSync(`${REF}/ds-loader.js`, "utf8");
const files = JSON.parse(loader.match(/var FILES = (\[[^\]]*\])/)[1]);
// quiet's own components (not in the reference): src/components/future, from the Claude Design
// "Future Components" concepts, rebuilt on quiet tokens. Appended after the reference ones.
const future = readdirSync("src/components/future")
	.filter((f) => f.endsWith(".jsx"))
	.map((f) => `future/${f.slice(0, -4)}`)
	.sort();
writeFileSync(
	"src/index.ts",
	`${HEADER}/// <reference path="./jsx-global.d.ts" />\n${[...files, ...future]
		.map((f) => `export * from "./components/${f}";`)
		.join(
			"\n",
		)}\nexport { QuietRoot, type QuietRootProps } from "./QuietRoot";\nexport { applyTheme, defaultTheme, type ThemeName, themeNames, themes } from "./styles/themes/themes";\nexport { ThemeProvider, useTheme } from "./styles/themes/ThemeProvider";\n`,
);

const html = readFileSync(`${REF}/components/index.html`, "utf8");
const script = html.match(/<script type="text\/babel">\n([\s\S]*)<\/script>/)[1];
const boot =
	/let DS;\nloadDS\('\.\.\/'\)\.then\(d => \{ DS = d; ReactDOM\.createRoot\(document\.getElementById\('root'\)\)\.render\(<App \/>\); \}\);\n$/;
if (!boot.test(script)) throw new Error("index.html boot line changed — update gen.mjs");
writeFileSync(
	"src/stories/catalog.generated.jsx",
	`${HEADER}import React from "react";\nimport * as DS from "../index";\n\n${script.replace(boot, "")}\nexport default App;\n`,
);
writeFileSync(
	"src/stories/catalog.generated.d.ts",
	`${HEADER}export default function App(): import("react").JSX.Element;\n`,
);
console.log(`index.ts: ${files.length} components; catalog: ${script.split("\n").length} lines`);
